### ISSUE TITLE
просьба проверить тестовое задание

### ISSUE THREAD

**Issue by suberg** [suberg/WYSIWYG#1]

**Comment by JSMonk** [comment]
1. Постарайтесь избавиться от `innerHTML`. Я тут чуть-чуть ваш clipboard сломал:

https://user-images.githubusercontent.com/10776615/104133456-5c0fd380-538c-11eb-99bc-f4eba5ecbaf8.mov

2. Постарайтесь использовать уже заданные стили в `styles/editor.css`

**Comment by suberg** [comment]
@JSMonk Спасибо за фидбэк!
Избавился от `innerHTML`, стили используются заданные, но с ними не сохраняется форматирование хедеров в Microsoft Office Online (хотя использую теги h1, h2), поэтому изначально были написаны свои.

**Comment by JSMonk** [comment]
Я всячески пытаюсь подобрать формулировку, но так или иначе получается очень большая подсказка 😄 
Могу сказать только, что сохранить стили можно и не одним способом)

**Comment by suberg** [comment]
Доработал. В заданных стилях размеры шрифта указаны в ремах, соответственно, чтобы сохранить стилизацию при копировании, нужно получить размер шрифта в пикселях с помощью метода `getComputedStyle`. В описании задачи указано, что при копировании текста в Word Online, стилизация (italic, хедеры и bold) остаются неизменными. Как я понимаю, у хедеров должен сохраниться только размер шрифта.

**Comment by JSMonk** [comment]
Не сохраняются стили при переносе в Microsoft Word Online:
<img width="212" alt="Screen Shot 2021-01-13 at 2 20 42 PM" src="https://user-images.githubusercontent.com/10776615/104451714-9951ac80-55aa-11eb-9a28-c687da2fea92.png">
<img width="610" alt="Screen Shot 2021-01-13 at 2 20 27 PM" src="https://user-images.githubusercontent.com/10776615/104451718-99ea4300-55aa-11eb-872f-73a562c76865.png">

**Comment by suberg** [comment]
Да, действительно, событие cut не обрабатывалось. Добавил.

**Comment by JSMonk** [comment]
Здравствуйте, Антон.
1. Меняется цвет заголовков при переносе содержимого в Microsoft Office Online:
<img width="243" alt="Screen Shot 2021-01-14 at 12 34 16 PM" src="https://user-images.githubusercontent.com/10776615/104579686-f447da00-5664-11eb-84c7-bc5f764c7062.png">
<img width="628" alt="Screen Shot 2021-01-14 at 12 34 11 PM" src="https://user-images.githubusercontent.com/10776615/104579689-f4e07080-5664-11eb-8314-bfbd3f678449.png">
2. Постарайтесь использовать уже заданные стили в `styles/editor.css`.

**Comment by suberg** [comment]
Артём, приветствую!
Внес правки:
1. Стили сохраняются при копировании текста
<img width="448" alt="Screenshot 2021-01-15 at 09 51 34" src="https://user-images.githubusercontent.com/18160956/104676707-7c3beb80-571a-11eb-98f4-1f1d8ebc9d90.png">
<img width="272" alt="Screenshot 2021-01-15 at 09 51 23" src="https://user-images.githubusercontent.com/18160956/104676711-7e9e4580-571a-11eb-97cc-acba78c148e1.png">

2. Для стилизации текста использовал классы `header1-text`, `header2-text`, `bold-text` и `italic-text`. Вроде ничего больше не упустил)

**Comment by JSMonk** [comment]
Здравствуйте, Антон.
Почти все хорошо, остался только последний баг :D
Можно редактировать содержимое вне редактора

https://user-images.githubusercontent.com/10776615/104790132-5b69a980-579f-11eb-8096-5e9f1910a605.mov

**Comment by suberg** [comment]
Спасибо, исправлено 👍

**Comment by JSMonk** [comment]
Здравствуйте, Антон.
Задание принято 👌 

Можно Вашу почту (если подписаны были на Patreon - то ту же что и на патреоне) и telegram-контакт (номер или ник, все-равно) для дублирования сообщений.

Пройдет некоторое количество времени (мы сдвинем старт на неделю вперед) и Вы получите ссылку на оплату и мы сообщим Вам дальнейшие шаги.

**Comment by suberg** [comment]
Отлично 🙂
Почта: yakunov94@gmail.com
Telegram: suberg
